### ISSUE TITLE
Błąd kompilacji na Windows + błąd kompilacji gdy ścieżka zawiera spacje

### ISSUE THREAD

**Issue by JaroslawPokropinski** [LechMadeyski/JavaMetrics#1]
Gdy są spacje:
java.io.FileNotFoundException: C:\Programming\University%20projects\PBR\JavaMetrics\target\test-classes\CsvReaderTestInputFile.csv (The system cannot find the path specified)

-- Na Windows
Failures: 
```
[ERROR]   ClassMetricStrategyTest.getClassAccessorMethods:43->lambda$getClassAccessorMethods$0:47 expected: <public int getSampleField() {

    return sampleField;
}> but was: <public int getSampleField() {
    return sampleField;
}>
```

**Comment by arekziobrowski** [comment]
Dzięki za zgłoszenie!

1. Problemem okazało się użycie klasy `java.net.URL`, która powodowała konwersję spacji w ścieżkach na "%20". Wprowadziłem ponowną konwersję w miejscu użycia - z tego co widziałem pojawiała się w przypadkach testowych wyłacznie.

2. Również problem przypadku testowego. Okazuje się, że Javaparser podczas parsowania wykorzystuje zależne od platformy znaki końca linii. Poprawiony przypadek testowy.
