### ISSUE TITLE
Wrong behavior of GitDownloader on Windows

### ISSUE THREAD

**Issue by kinga-pwr** [LechMadeyski/JavaMetrics#2]
Method cleanUp in GitDownloader has a process execution:
`ProcessBuilder pb = new ProcessBuilder("rm", "-rf", repositoryPath);`
Command which was used is not suitable for Windows and results in obtaining status code 128.

A suggested solution would be adding a dedicated Windows command:
`new ProcessBuilder("cmd.exe", "/c", "rmdir /Q /S " + repositoryPath)`

**Comment by arekziobrowski** [comment]
Thank you!
Instead of using `rmdir` command to achieve cross-platform directory removal support I decided to use Java 7+ `SimpleFileVisitor<Path>` and `Files.walkFileTree`.

Now the responsibility for cross-platform support is on JVM side :)
